import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import BraintreeDropIn from '../components/braintreeButton'
import ButtonPayPal from '../components/buttonsPayPal'
import styles from '../styles/Home.module.css'
import {Col, Container, Input, Row, Button} from "reactstrap";

export default function BrainTreeTests() {
  const [checkout, setCheckout] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/braintreeTest">braintree Test!</a>
        </h1>
        <h1 className={styles.title}>
          Go <a href="/">Home!</a>
        </h1>

        <BraintreeDropIn />
        
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
